2019-07-15 16:30:00,577 ERROR: Exception on /index [GET] [in C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Марсель\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\PyProjects\mywebserver\app\routes.py", line 24, in index
    if form.validate_on_submit():
TypeError: validate_on_submit() missing 1 required positional argument: 'self'
2019-07-15 16:30:01,423 ERROR: Exception on /index [GET] [in C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Марсель\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\PyProjects\mywebserver\app\routes.py", line 24, in index
    if form.validate_on_submit():
TypeError: validate_on_submit() missing 1 required positional argument: 'self'
2019-07-15 16:31:28,191 INFO: Microblog startup [in D:\PyProjects\mywebserver\app\__init__.py:47]
2019-07-15 16:31:32,644 ERROR: Exception on /index [GET] [in C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Марсель\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\PyProjects\mywebserver\app\routes.py", line 24, in index
    if form.validate_on_submit():
TypeError: validate_on_submit() missing 1 required positional argument: 'self'
2019-07-15 16:31:34,901 ERROR: Exception on /index [GET] [in C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Марсель\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\PyProjects\mywebserver\app\routes.py", line 24, in index
    if form.validate_on_submit():
TypeError: validate_on_submit() missing 1 required positional argument: 'self'
2019-07-15 16:32:04,856 ERROR: Exception on /index [GET] [in C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Марсель\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\PyProjects\mywebserver\app\routes.py", line 24, in index
    if form.validate_on_submit():
TypeError: validate_on_submit() missing 1 required positional argument: 'self'
2019-07-15 16:32:46,301 ERROR: Exception on /index [GET] [in C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Марсель\AppData\Roaming\Python\Python37\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Марсель\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\PyProjects\mywebserver\app\routes.py", line 24, in index
    if form.validate_on_submit():
TypeError: validate_on_submit() missing 1 required positional argument: 'self'
2019-07-15 16:34:06,514 INFO: Microblog startup [in D:\PyProjects\mywebserver\app\__init__.py:47]
2019-07-15 20:42:28,156 INFO: Microblog startup [in D:\PyProjects\mywebserver\app\__init__.py:47]
2019-07-15 21:25:22,691 INFO: Microblog startup [in D:\PyProjects\mywebserver\app\__init__.py:48]
2019-07-15 21:42:42,536 INFO: Microblog startup [in D:\PyProjects\mywebserver\app\__init__.py:48]
2019-07-15 21:44:43,893 INFO: Microblog startup [in D:\PyProjects\mywebserver\app\__init__.py:48]
2019-07-15 21:46:06,435 INFO: Microblog startup [in D:\PyProjects\mywebserver\app\__init__.py:48]
2019-07-15 21:47:51,931 INFO: Microblog startup [in D:\PyProjects\mywebserver\app\__init__.py:48]
2019-07-15 21:51:48,503 INFO: Microblog startup [in D:\PyProjects\mywebserver\app\__init__.py:48]
2019-07-15 21:53:26,720 INFO: Microblog startup [in D:\PyProjects\mywebserver\app\__init__.py:48]
2019-07-15 22:02:14,739 INFO: Microblog startup [in D:\PyProjects\mywebserver\app\__init__.py:48]
2019-07-15 22:06:18,615 INFO: Microblog startup [in D:\PyProjects\mywebserver\app\__init__.py:48]
2019-07-15 22:08:06,140 INFO: Microblog startup [in D:\PyProjects\mywebserver\app\__init__.py:48]
